input {
  # S3 input plugin
  # https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html#plugins-inputs-s3-options
  s3 {
    bucket => "${AWS_S3_BUCKET}"                  # The name of the S3 bucket. Required.
    region => "${AWS_S3_REGION}"                  # The AWS Region. Default value is "us-east-1"
    prefix => "${AWS_S3_PREFIX}"                  # If specified, the prefix of filenames in the bucket must match (not a regexp)
    backup_to_dir => "${AWS_S3_BACKUP_DIR}"       # Path of a local directory to backup processed files to. Default is null.
    delete => "${AWS_S3_DELETE:false}"            # Whether to delete processed files from the original bucket. Default is false.
    watch_for_new_files => "${AWS_S3_WATCH:true}" # Whether or not to watch for new files. Default is true. Disabling this option causes the input to close itself after processing the files from a single listing.
    codec => plain                                # The codec used for input data. Default is plain. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.
  }
}

filter {
  # JSON filter plugin
  # https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html#plugins-filters-json-options
  json {
    source => "message"
  }

  # Date filter plugin
  # https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-options
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    timezone => "UTC"
  }

  # Drop if date parsing fails
  if "_dateparsefailure" in [tags] {
    drop { }
  }

  # GeoIP filter plugin
  # https://www.elastic.oco/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-options
  geoip {
    source => "remote_addr"
    target => "geoip"
  }

  # Mutate filter plugin
  # https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-options 
  mutate {
    remove_field => [
      "[event][original]"
    ]
    add_field => {
      "s3_source_file" => "%{[@metadata][s3][key]}"
      "log_type" => "wpvip_http"
      "environment" => "production"
    }
    convert => {
      "asn"              => "integer"
      "body_bytes_sent"  => "integer"
      "client_site_id"   => "integer"
      "request_time"     => "float"
      "status"           => "integer"
    }
  }

  # Ruby filter to parse the request_url and generate additional derived fields
  ruby {
    code => "
      url = event.get('request_url')
      if url
        first_dir = url.split('/')[1]
        event.set('first_dir', '/' + first_dir) if first_dir

        no_qs = url.split(/[?#]/).first
        event.set('request_url_no_qs', no_qs)

        args = url.sub(no_qs.to_s, '')
        event.set('request_url_args', args)
      end
    "
  }
}

# Output plugin
# https://www.elastic.co/guide/en/logstash/current/output-plugins.html#output-plugins 
output {
  elasticsearch {
    hosts => ["//elasticsearch:9200"]
    index => "wpvip-logs-%{+YYYY.MM.dd}"
    manage_template => false
  }
  
  # Enable debug output
  stdout { codec => rubydebug }
}